### ISSUE TITLE
Extend Certificate resource

### ISSUE THREAD

**Issue by josephrodriguez** [josephrodriguez/helm-charts#19]
Add support for the properties:

```
  secretName: my-certificate-secret
  commonName: "myName"
  issuerRef:
    name: ca-issuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: example-com-tls-keystore
        key: password
```
